### ISSUE TITLE
Documentation enhancements

### ISSUE THREAD

**Issue by dariocravero** [padrino/padrino-framework#1137]
# List of features to document

## Components
- [ ] Explain `.components`.
- [ ] How to change ORM,
- [ ] How to change renderer,
- [ ] How to change styles processor,
- [ ] How to change scripts,
- [ ] How to change database adapter?

## ...
- [ ] Document invoke_hooks (#1098)
- [ ] Cleanup documentation for fields_for (#939)
- [ ] Gemified apps (added to generation docs)
  - [ ] Detailed explanation on how to handle gemified apps
- [ ] Performance tools guide
- [ ] Project modules (re 0.11 release)
- [ ] Document [padrino-flash](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/application/flash.rb) better. Particularly what the story is with `now` and `next`. Also, add some comments to the code from the original repo (https://github.com/Cirex/padrino-flash).
- [ ] Explain [`Padrino.dependency_paths`](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/loader.rb#L184-L196).
- [ ] Document [how to write rake tasks](https://github.com/padrino/padrino-framework/issues/1189#issuecomment-15502790).
- [ ] Document CSRF, how it relates to post requests, how to disable it (app-wide or controller-level)
- [ ] Document (See #1475) how to access current request controller and action names
- [ ] Document app gemming and starting and the need of special placement for log, tmp, configs

## Testing
- [ ] How to set the current account  (or the session in general) while testing controllers#1198.

Let's build this list up! :)

**Comment by Quintasan** [comment]
I just got this idea from #neovim IRC channel which has a dedicated bot to releat the messages between Gitter and IRC. They use [finnp/gitter-irc-bot](https://github.com/finnp/gitter-irc-bot). Perhaps it would be good idea to get something similar.

**Comment by nesquena** [comment]
@wikimatze This represents a list of some of the most obvious missing or incomplete documentation. Any help in augmenting the guides with these would be much appreciated.

**Comment by ujifgc** [comment]
This issue was moved to padrino/padrino-docs#98
