### ISSUE TITLE
Enhanced admin roadmap for 0.12.0

### ISSUE THREAD

**Issue by dariocravero** [padrino/padrino-framework#1153]
- [ ] Mobile friendly. It has to behave at least a bit better.
- [ ] Remove any inline CSS that's remaning.
- [ ] Normalise the CSS structure.
- [ ] Provide the user with minimised and gziped assets for production.
- [ ] Document structure, layouts, etc.
- [ ] Separate CSS for login, errors and application.
