### ISSUE TITLE
Enhanced admin roadmap for 1.0.0

### ISSUE THREAD

**Issue by dariocravero** [padrino/padrino-framework#1154]
- [ ] Revamp the concept and make it completely data driven.
- [ ] Super dynamic. Think Backbone and async.
- [ ] Super mobile friendly. It's better now than it was before but there's still lots of work to be done.
- [ ] Add filters, search, infinite-scroll or pagination, etc.
- [ ] Use whatever pipeline to compile assets the app uses beneath?
- [ ] Impersonation feature. See #156. (maybe as an addon/contrib?)
- [ ] Forgot your password feature. (maybe as an addon/contrib?)
- [ ] Foreign key support #1524

Let's discuss this in more depth @padrino/core-members, @tomatuxtemple and everyone else :)

**Comment by kkirsche** [comment]
How would I go about assisting with rewriting the admin front end interface? I'd be interested in helping put together a new admin section using Bootstrap and Angular as this combo would work nicely

**Comment by dariocravero** [comment]
@kkirsche thanks for your help. The current implementation of the admin is already using bootstrap.
I would be slightly concerned about forcing a UI framework but I'd say that, true to the agnostic approach of Padrino, it might be a good idea to open the door for multiple UI implementations of it. We would need to finalise the admin's internal API that @skade suggested a while ago before jumping on this though I think.
