### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by angeloashmore** [padrino/padrino-framework#1964]
Late last year, a discussion started to create a new Padrino website (#1826). It looks like things have paused since February, but let's pick it up again.

There were discussions to get the site site up with the 0.13.0 release so let's make that the goal.

**Repo**: https://github.com/angeloashmore/padrino-web

Please clone and try it out.

## Current Screenshots

**Desktop**

<img width="150" alt="screen shot 2015-09-10 at 1 23 35 am" src="https://cloud.githubusercontent.com/assets/8601064/9787033/a7257958-575a-11e5-86c5-e5c5995bd4fb.png"> <img width="150" alt="screen shot 2015-09-10 at 1 25 29 am" src="https://cloud.githubusercontent.com/assets/8601064/9787053/e1fb3f86-575a-11e5-8d2a-6d6c573bcdc0.png"> <img width="150" alt="screen shot 2015-09-10 at 1 24 03 am" src="https://cloud.githubusercontent.com/assets/8601064/9787042/c1e66ca2-575a-11e5-9277-a486dac40ce9.png"> <img width="150" alt="screen shot 2015-09-10 at 1 25 11 am" src="https://cloud.githubusercontent.com/assets/8601064/9787057/f9fcb218-575a-11e5-83d5-eeced6e8745f.png">

**Mobile**

<img width="150" alt="screen shot 2015-09-10 at 2 29 23 pm" src="https://cloud.githubusercontent.com/assets/8601064/9804340/5b745ca4-57c8-11e5-8f24-886e40e22621.png"> <img width="150" alt="screen shot 2015-09-10 at 1 27 56 am" src="https://cloud.githubusercontent.com/assets/8601064/9787091/3fd182d2-575b-11e5-9e4a-2276d139ea5d.png"> <img width="150" alt="screen shot 2015-09-10 at 1 28 17 am" src="https://cloud.githubusercontent.com/assets/8601064/9787089/3fa6eaae-575b-11e5-9563-16247e686767.png"> <img width="150" alt="screen shot 2015-09-10 at 1 28 22 am" src="https://cloud.githubusercontent.com/assets/8601064/9787090/3fd13980-575b-11e5-9897-6f75310d6dfb.png">

## TODO

See the issues on the repository: https://github.com/angeloashmore/padrino-web/issues

Please let me know if I am missing anything.

**Comment by hbrysiewicz** [comment]
I'm happy to help out where I can. Will clone and check things out. Feel free to contact me to coordinate :)

**Comment by angeloashmore** [comment]
@hbrysiewicz Good to hear! I've opened some issues on the repository to keep track of everything. Feel free to work on them and submit a PR.

https://github.com/angeloashmore/padrino-web/issues

**Comment by nesquena** [comment]
Thank you @angeloashmore for putting this together. A few related links:

* This is the [original thread](https://github.com/padrino/padrino-framework/issues/1826) on a new site with @wikimatze 
* Here was the repo we were working out of: https://github.com/padrino/padrino-new-web
* Older thread [discussing a new site](https://github.com/padrino/padrino-web/issues/30)

Is this effort related to the efforts @wikimatze was working on a separate?

**Comment by angeloashmore** [comment]
@nesquena This is a separate effort as it uses a different build system (Middleman, which uses padrino-helpers, instead of Jekyll) and a different design.

I did take some of the Markdown resources from the `padrino-new-web` repo (articles, home page copy, etc.).

It's also a bit more simplified version of the current site rather than a complete port with a new design. I feel we can remove some of the cruft of the current site and keep it simple and light.

**Comment by wikimatze** [comment]
Hi @angeloashmore thanks for putting up a second design, think now that we have two versions of the old website, we can surely put up either your or mine site. Of course, can you take markdown of my site to your version. I've no problem with it.

Beside, middleman would be something new to learn for me. Hope to get it out this year, since I start it last year. Let's finally make a decision about the new website and where we are gone to host it.

Best

Matthias

**Comment by angeloashmore** [comment]
I think GitHub Pages will be the simplest approach since we would be hosting the code here anyway. It's also free! :smile:

Building and deploying the site is as easy as:

~~~ sh
middleman build && middleman deploy
~~~

This will build the site and push to the `gh-pages` branch of the repo. The domain would point to the GitHub pages url accordingly ([guide here][0]).

[0]: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by angeloashmore** [comment]
If you want to preview the site, check it out here: http://angeloashmore.github.io/padrino-web/

Note: I'm having issues setting up Middleman to build link URLs properly, so you'll need to add `padrino-web/` after `github.io/` if you click on a link. GitHub pages deploys to a subdirectory, so it messes with the relativeness of the links.

**Comment by wikimatze** [comment]
I'll have a look and help porting some of my stuff to your project (I like your design much more the more often I look at it :smile: ).

**Comment by wikimatze** [comment]
I ported most of the blog posts to your repository: https://github.com/angeloashmore/padrino-web/pull/4

**Comment by nesquena** [comment]
@wikimatze @angeloashmore I really like this site, what steps are left for us to be able to deploy this? what content is missing?

**Comment by angeloashmore** [comment]
@nesquena Not much else is needed:

* Port remaining blog posts
  * Not all blog posts were present in the https://github.com/padrino/padrino-web repo. I'm guessing the entries are now saved directly in a database using something like Padrino Admin? Any chance these are readily available in Markdown somewhere?
* Link buttons on the homepage to the relevant guide
* Update homepage to reflect newest release (0.13.0)

**Comment by nesquena** [comment]
@angeloashmore I'll take care of porting the blog posts over to the new site. Anything else you'd need from me to complete the remaining items?

Thanks again for helping us have a new and modern site!

**Comment by angeloashmore** [comment]
@nesquena Awesome! I can complete the other two bullet points later today.

There are some other changes I would like to implement down the road (better guide organization, search, …), but its current state is launch-ready.

Regarding hosting, how would we go about getting padrinorb.com connected? Should we move the repo to the @padrinorb group?

**Comment by nesquena** [comment]
@angeloashmore sweet, will port over blog posts this weekend.

Can you move the repo over in admin tab to padrino-framework org?

Regarding hosting, I will host the site on an existing VPS I have and we will just need to work with @DAddYE to switch over DNS once it's all ready.

**Comment by ujifgc** [comment]
One little thing before switching over. http://www.padrinorb.com/ is now indexed by Google and things. Do we just don't care about it or do we add a redirect map for the old URIs?

**Comment by nesquena** [comment]
@angeloashmore @ujifgc we have the blog, guides, pages all here https://github.com/padrino/padrino-framework/tree/master/padrino-docs what should we do with that in contrast to https://github.com/angeloashmore/padrino-web/tree/master/source?

**Comment by nesquena** [comment]
@angeloashmore can you add me as a collaborator to https://github.com/angeloashmore/padrino-web so I can transfer the repo to the padrino org?

**Comment by wikimatze** [comment]
Awesome news to see that it is going on with the new website. The point from @ujifgc is a good one: do we care about the google index and write some rewrite rules? Or should we just skip this step and consider the new indexing?

**Comment by nesquena** [comment]
@wikimatze @angeloashmore I think it'd be best if we would setup redirects for posts and guides at least but if that's going to be a huge blocker we should let it go.

I have added a few issues here: https://github.com/angeloashmore/padrino-web/issues in particular about making sure we have the correct content for blog posts and guides. Also about consolidating content. Right now, we have the content in [padrino-docs](https://github.com/padrino/padrino-framework/tree/master/padrino-docs) as well as [source](https://github.com/angeloashmore/padrino-web/tree/master/source). I also moved all the latest guides from padrinorb.com (which has separate changes) to [this temporary repo](https://github.com/padrino/temp-guides/tree/master). 

What do you all think is the best way to move this forward?

**Comment by angeloashmore** [comment]
@nesquena Just added you as a collaborator.

*Guides/Docs*: It seems best to keep guides/docs in a separate repo from the website. The website repo can reference the docs repo as a submodule. This way contributors can maintain docs separate from the website structure (so long as the frontmatter follows a certain standard).

*URL Redirects*: On first glance, it looks like most of the pages will share the same URL as long as the page titles/filenames are the same. We can do a quick audit, but I vote we don't worry too much about it.

**Comment by nesquena** [comment]
@angeloashmore I am not able to switch the repo to the padrino org. I have just invited you as a member of our org so you can [transfer over the repo](https://help.github.com/articles/transferring-a-repository). Can you move it over as outlined in that guide?

I agree we should make the guides/docs a separate repo. What do you think about having it stored in the padrino-framework repo as it is now in [padrino-docs](https://github.com/padrino/padrino-framework/tree/master/padrino-docs)? Or should it be it's own repo. Either way, can you and @wikimatze help merge the blog, guides, etc into a repo which becomes a submodule for the site?

**Comment by namusyaka** [comment]
Sorry for the late reply, I agreed.

**Comment by ujifgc** [comment]
I disagree on moving guides away from main repository to a separate one. For me it's much more convenient to work with one repository.

**Comment by wikimatze** [comment]
I would also would like to have one repository for the website. We could just add a subfolder with the guides/doc and one with posts.

**Comment by nesquena** [comment]
@ujifgc just to clarify, are you recommending we leave the posts/guides in the [main repo](https://github.com/padrino/padrino-framework/tree/master/padrino-docs) as it is now and then have this website display the content from that folder? 

@wikimatze are you suggesting that we keep the website as it is now with guides/posts as part of the website repo or are you saying the website should live inside the padrino-framework repo?

@namusyaka which approach did you think made sense?

If I could pick, I would say it is nice having the [docs in the main repo](https://github.com/padrino/padrino-framework/tree/master/padrino-docs) and then the website in it's own repo which sources the guides / blogs from there but I am fine with any of these.

**Comment by ujifgc** [comment]
@nesquena yes. I think website should import main repository and compile it's pages from padrino-docs. If it's inconvenient for the access rights reason, we could move padrino-docs back to https://github.com/padrino/padrino-docs and have it subrepoed to both padrino-web and padrino-framework so the docs are always from one source.

**Comment by nesquena** [comment]
:+1: on the idea of having it as a submodule for both padrino-framework and padrino-web so it can be accessed from either source. What do the rest of you think?

**Comment by angeloashmore** [comment]
1. Move padrino-docs from padrino/padrino-framework back to padrino/padrino-docs
2. Add padrino-docs as a submodule to padrino/padrino-framework and padrino/padrino-web

It looks like [padrino-docs/pages][0] is no longer needed

**Comment by nesquena** [comment]
@angeloashmore Great!

> Move padrino-docs from padrino/padrino-framework back to padrino/padrino-docs

Moved to: https://github.com/padrino/padrino-docs

> Add padrino-docs as a submodule to padrino/padrino-framework

Done. 82bbd03d59857609344e046927e236bce3bf1494

> Add padrino-docs as a submodule to padrino/padrino-web-new

Done. https://github.com/padrino/padrino-web-new/commit/058bbd53b6167a8af8005324819ed8d50939e302

Can you or @wikimatze help with consolidate the blog posts to make sure we don't lose the tags and other metadata in docs. The other posts in new-web have some posts missing from docs. I moved over the latest 0.13.0 blog posts though that were missing from both. Then we need to do 3 and 4.

**Comment by wikimatze** [comment]
I'm with the submodule approach now, but we need to update the README and explain how to check out the subrepo and how to commit those changes.

I preserved the tags (categories) of the posts under <https://github.com/wikimatze/padrinorb-website/tree/master/_posts> and could check, if they are still existing on the new repo. It seems like we get things get going much faster then the last years - we are actually making bis progress.

I can take care of step 4. Think step three shouldn't be a problem in middleman.

**Comment by Kuraiko** [comment]
It's a bit sad that two people have contributed new & updated websites (already over a year ago) and still nothing changed... http://www.padrinorb.com/ has still the old and outdated website... 

What's the reason that nobody adopts @wikimatze's or @angeloashmore's design and work to the official website?

**Comment by nesquena** [comment]
* Site: https://github.com/padrino/padrino-web-new
* Docs: https://github.com/padrino/padrino-docs
* Latest versions of the guides: https://github.com/padrino/temp-guides/tree/master

@Kuraiko we are very close now, but have a few more steps before completing the conversion, mostly just ensuring we have all the content in the new website. Would you like to help us get to the finish line?

Final steps:

1. Make sure we have all the blog posts in the post folder 
    - Ensure the front-matter contains meta data for each post including tags
    - Tags (categories) for the posts are here: https://github.com/wikimatze/padrinorb-website/tree/master/_posts
2. Alias /posts to /blog in padrino-web
3. Fix anything broken in padrino-web due to the change to padrino-docs
4. update the README and explain how to check out the subrepo and how to commit those changes.

**Comment by DAddYE** [comment]
As soon as everything is ready, feel free to publish on heroku or let me know if you guys need a vps.

I’ll then change/setup the dns change and certs (https).

—
DAddYE

**Comment by wikimatze** [comment]
@Kuraiko thanks for bringing this up. I'll try to work on those things and try to get it ready till Christmas.

**Comment by DAddYE** [comment]
@wikimatze we should do it within few days since the current hosting is expiring

**Comment by Kuraiko** [comment]
@wikimatze Meld dich wenn man dir bei etwas helfen kann!

**Comment by wikimatze** [comment]
I'll work on 1. Ensuring all posts are there and preserving the tags. I'll push the changes to https://github.com/wikimatze/padrinorb-website and we can put them later on to the middleman repo.

@Kuraiko das erste mal, das ich Deutsch auf github rede :).

**Comment by nesquena** [comment]
@wikimatze ok great thanks, if you can get all the posts with tags correct and then move them into https://github.com/padrino/padrino-docs/tree/master/posts that would be super helpful. @angeloashmore can you help with 2 and 3?

**Comment by wikimatze** [comment]
@nesquena I'll put them there, when I'm finished. Can you give me contribution rights?

**Comment by nesquena** [comment]
@wikimatze yep you should have full access now.

**Comment by wikimatze** [comment]
@nesquena it is working, thanks.

**Comment by nesquena** [comment]
@wikimatze @angeloashmore @DAddYE We had to switch over the website to the new version:

* Github Page: http://padrino.github.io/padrino-web-new/
* Domain Redirected: http://padrinorb.com
* Gh-Pages Branch: https://github.com/padrino/padrino-web-new/tree/gh-pages

How do we deploy updates from https://github.com/padrino/padrino-web-new to gh-pages? Looks like it may be as simple as running a rake task in the project? Appears to be working but we need to add the updated posts and guides.

**Comment by nesquena** [comment]
Just wanted to follow up as I figured this out. The site is live and ready to go! /cc @padrino/core-members 

- [x] Make sure we have all the blog posts in the posts folder (Thanks @wikimatze)
- [x] Alias `/posts` to `/blog` in [padrino-web-new](https://github.com/padrino/padrino-web-new)
- [x] Fix anything broken in [padrino-web-new](https://github.com/padrino/padrino-web-new) due to the change over to padrino-docs
- [x] Update the README and explain how to check out the subrepo and how to commit those changes.

Now, changes can be made in padrino-docs and committed. Once changes are committed to that repository, we can run `rake publish` which will update the submodule, build the static site and deploy to the gh-pages branch automatically!

**Comment by wikimatze** [comment]
Since the site is live, are we planning to do some tracking (e.g. Piwik and/or Google Analytics or does github pages offers somethink like this) or do we not care about it?

And how is the API page build? I know it's build on YARD (which was done in the past from @postmodern). Just want to understand how things work.

**Comment by nesquena** [comment]
@wikimatze Yep, we should definitely add GA tracking http://stackoverflow.com/questions/17207458/how-to-add-google-analytics-tracking-id-to-github-pages. That is definitely an important action item.

> And how is the API page build? I know it's build on YARD (which was done in the past from @postmodern). Just want to understand how things work.

Good question: http://www.rubydoc.info/github/padrino/padrino-framework appears to be built last on Nov 29th. I think it can be re-built anytime by going to http://www.rubydoc.info/find/github?q=padrino-framework and clicking the "reload" icon.

**Comment by wikimatze** [comment]
I clicked "reload" icon and now we got a fresh version under http://www.rubydoc.info/github/padrino/padrino-framework/master. Can we automate this task for every commit we made to the master? Think a github hook should be suitable for this.
